service: halcyon-rest-api

provider:
    name: aws
    runtime: nodejs8.10
    stage: dev
    region: eu-west-1
    memorySize: 1024
    logRetentionInDays: 3
    environment:
        MONGODB_URI: ${env:MONGODB_URI, ''}
        JWT_SECURITYKEY: ${env:JWT_SECURITYKEY, ''}
        SEED_EMAILADDRESS: ${env:SEED_EMAILADDRESS, ''}
        SEED_PASSWORD: ${env:SEED_PASSWORD, ''}
        EMAIL_HOST: ${env:EMAIL_HOST, ''}
        EMAIL_PORT: ${env:EMAIL_PORT, ''}
        EMAIL_USERNAME: ${env:EMAIL_USERNAME, ''}
        EMAIL_PASSWORD: ${env:EMAIL_PASSWORD, ''}
        EMAIL_NOREPLY: ${env:EMAIL_NOREPLY, ''}
        FACEBOOK_APPID: ${env:FACEBOOK_APPID, ''}
        FACEBOOK_APPSECRET: ${env:FACEBOOK_APPSECRET, ''}
        GOOGLE_CLIENTID: ${env:GOOGLE_CLIENTID, ''}

plugins:
    - serverless-offline
    - serverless-dotenv-plugin

functions:
    app:
        handler: dist/serverless.handler
        events:
            - http: ANY /
            - http: 'ANY {proxy+}'

custom:
    serverless-offline:
        port: 3001
